# 共通のeslintrc

root: true

extends:
  - airbnb-base
  - plugin:promise/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint

parser: '@typescript-eslint/parser'

env:
  browser: true

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: false

settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .js

plugins:
  - '@typescript-eslint'

rules:
  # use only console.debug, console.warn, console.error
  no-console:
    - error
    - allow: [debug, warn, error]

  # line spacing
  padding-line-between-statements:
    - error
    - { blankLine: always, prev: '*', next: return }
    - { blankLine: any, prev: export, next: export }
    - { blankLine: always, prev: '*', next: if }
    - { blankLine: always, prev: '*', next: const }
    - { blankLine: always, prev: const, next: '*' }
    - { blankLine: any, prev: const, next: const }
    - { blankLine: always, prev: '*', next: default }
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true

  # function style
  func-style:
    - error
    - expression

  # allow props reassign by variable name
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor: []

  # import extension
  import/extensions:
    - error
    - never

  # avoid default export
  import/prefer-default-export:
    - off
  import/no-default-export:
    - error

  # import order formatting
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  # required return type
  '@typescript-eslint/explicit-module-boundary-types':
    - error

  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true

  # use "_" prefix for unused variable
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'

  # overwrite no-use-before-define
  no-use-before-define:
    - off
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: true
      classes: true
      variables: true
      enums: true
      typedefs: true

  no-bitwise:
    - off

  no-underscore-dangle:
    - error
    - allow:
        - __FIRST__
        - __LAST__
        - __NEXT__
        - __SIZE__
